### PR TITLE
Add Pepe chain

### PR DESCRIPTION
**Pull request by benaadams**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):

https://pepe-chain.vip/

#### Provide a link to your privacy policy:

Unknown

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

@pepechainpc

### CODE REVIEW

**Comment by realdealshaman** [comment]
@benaadams Hi and thanks for the pr. To add a new network to chainlist, please submit your PR here first: https://github.com/ethereum-lists/chains
thanks

**Comment by benaadams** [comment]
> @benaadams Hi and thanks for the pr. To add a new network to chainlist, please submit your PR here first: https://github.com/ethereum-lists/chains thanks

Thank you; have added PR https://github.com/ethereum-lists/chains/pull/3210

**Comment by benaadams** [comment]
@realdealshaman is merged to ethereum-lists now

**Comment by benaadams** [comment]
Not happy with this project so won't put my name to this PR

**Pull request closed without merging**
