### PR TITLE
Add greenfield RPC

### PR DESCRIPTION
**Pull request by Pythonberg1997**
The necessary information has been filled out in the document

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @Pythonberg1997 thanks for the pr. To add a new chain, please submit your pull request here first: https://github.com/ethereum-lists/chains

**Review by merelin1576 — APPROVED** [review]

**Comment by Pythonberg1997** [comment]
> Hey @Pythonberg1997 thanks for the pr. To add a new chain, please submit your pull request here first: https://github.com/ethereum-lists/chains

https://github.com/ethereum-lists/chains/pull/3679

The pr is here

**Review by melissamforbs — COMMENTED** [review]
😀

**Review by melissamforbs — COMMENTED** [review]
😀

**Pull request closed without merging**
