### PR TITLE
Update Chain ID 2323 and 2332 SomaNetwork

### PR DESCRIPTION
**Pull request by somanetwork**
add chain id 2332 (Soma mainnet)
add chain id 2323 (Soma Testnet)

If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by somanetwork** [comment]
I have authorized Vercel, but the status is still waiting, please approval

**Comment by realdealshaman** [comment]
@somanetwork to add a new network you need to submit the PR to the following repo: https://github.com/ethereum-lists/chains

**Comment by somanetwork** [comment]
> @somanetwork to add a new network you need to submit the PR to the following repo: https://github.com/ethereum-lists/chains
Soma done chainid.network please check

**Comment by somanetwork** [comment]
how sir, please Up

**Pull request closed without merging**
