### PR TITLE
Add Echelon

### PR DESCRIPTION
**Pull request by echelonfoundation**
Add Echelon (Chain ID: 3000) and two RPCs.

https://ech.network

### CODE REVIEW

**Comment by realdealshaman** [comment]
Please submit your PR to the following repo to have a new chain added: https://github.com/ethereum-lists/chains

**Comment by echelonfoundation** [comment]
> Please submit your PR to the following repo to have a new chain added: https://github.com/ethereum-lists/chains



> Please submit your PR to the following repo to have a new chain added: https://github.com/ethereum-lists/chains

https://github.com/ethereum-lists/chains/pull/1096

**Comment by echelonfoundation** [comment]
> Please submit your PR to the following repo to have a new chain added: https://github.com/ethereum-lists/chains



> Please submit your PR to the following repo to have a new chain added: https://github.com/ethereum-lists/chains

https://github.com/ethereum-lists/chains/pull/1096

**Comment by realdealshaman** [comment]
Once your PR is merged there, the network will also show up on our Chainlist page

**Comment by echelonfoundation** [comment]
> Once your PR is merged there, the network will also show up on our Chainlist page

Great, thanks, just waiting! :)

**Comment by echelonfoundation** [comment]
Why close this? Just waiting on the chainlist merge on the PR...

**Pull request closed without merging**
