### PR TITLE
Update extraRpcs.js

### PR DESCRIPTION
**Pull request by 4everlandorg**
The RPC service offering on 4EVERLAND has been incorporated, accompanied by synchronized updates to the associated support information, encompassing:
- Ethereum Mainnet
- Ethereum Sepolia Testnet
- Binance Smart Chain (BSC) Mainnet
- Binance Smart Chain (BSC) Testnet
- Optimism Mainnet
- Taiko Mainnet
- Taiko Testnet

If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://dashboard.4everland.org/rpc

#### Provide a link to your privacy policy:
https://docs.4everland.org/more/security

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey, @4everlandorg please add a direct quote from your privacy policy to the privacyStatement

**Comment by 4everlandorg** [comment]
> Hey, @4everlandorg please add a direct quote from your privacy policy to the privacyStatement

Hey, @realdealshaman, thanks for the information. We have already added the link to the privacy policy as per your request.

**Comment by realdealshaman** [comment]
@4everlandorg this section: Information Collected Automatically, says that you do collect data, if you add within the privacy policy the amount of time you hold data before deleting it, we can add tracking as "limited" otherwise we'd simply need to change it to "yes"

**Comment by 4everlandorg** [comment]
> @4everlandorg this section: Information Collected Automatically, says that you do collect data, if you add within the privacy policy the amount of time you hold data before deleting it, we can add tracking as "limited" otherwise we'd simply need to change it to "yes"

Hey @realdealshaman, thanks for telling. We have updated the statement.

**Pull request merged**
