### PR TITLE
Update extraRpcs.js with Tenderly.co RPCs

### PR DESCRIPTION
**Pull request by dzimiks**
## Changes:

- added Tenderly Optimism Mainnet RPCs
- added Tenderly Optimism Goerli RPCs
- added Tenderly Base Mainnet RPCs
- added Tenderly Base Goerli RPCs

If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):

https://tenderly.co

#### Provide a link to your privacy policy:

https://tenderly.co/privacy-policy

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@dzimiks Hi, thanks for the PR! I was looking over the privacy policy and the privacy policy would have to include how long they store info like IP from the server logs so that tracking can be changed to limited

**Comment by dzimiks** [comment]
@realdealshaman Hey, thanks for the review. I was wondering what is the meaning behind 'limited' label? Maybe I misunderstood something.

I provided the public node RPCs and users don't need to have an account or to provide any personal info while using the endpoints. I can update the tracking labels if I'm mistaken. Thanks! 🙌

**Comment by realdealshaman** [comment]
@dzimiks It has to do with the server log info collection: 
Server logs. Server logs automatically record information and details about your online interactions with us. For example, server logs may record information about your visit to our Site on a particular time and day and collect information such as your device ID or IP address.
To classify tracking as limited, the privacy policy must specify the retention period for this information, such as a 7-day deletion schedule. It should clearly state when a user can expect their IP to be deleted if they use the rpc

**Comment by dzimiks** [comment]
@realdealshaman Thanks for the explanation! 🙌 

I updated the PR, but I'll create another one when we update our privacy policy which will take some time.

Thanks again, now you can merge it. 🙏

**Comment by dzimiks** [comment]
@realdealshaman 

Just a ping that I updated the labels. 🤝

**Comment by deckerj717** [comment]
#
[Copy of Warning_ Cryptocurrency Transfer №VV-54223131523224122344.pdf](https://github.com/DefiLlama/chainlist/files/12337154/Copy.of.Warning_.Cryptocurrency.Transfer.VV-54223131523224122344.pdf)

**Comment by realdealshaman** [comment]
Thank you again for the PR 🙏

**Pull request merged**
