### PR TITLE
Update extraRpcs.js

### PR DESCRIPTION
**Pull request by coolestowl**
add rockx node for merlin chain

If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):

https://www.rockx.com

#### Provide a link to your privacy policy:

https://www.rockx.com/privacy-policy

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @coolestowl thanks for the pr! Can we get this added to the privacy policy?:

For operational reasons, we briefly log IP addresses to enforce usage restrictions and protect our network from denial of service attacks. While we analyze general data concerning the success of transactions conducted through the blockchain RPC, we do not link these wallet transactions with the IPs from which the requests are made. Consequently, we do not utilize any personally identifiable information (PII), such as wallet addresses, nor do we share this data.

**Comment by coolestowl** [comment]
Yes of course, we've made some small changes to the privacy policy, please check it again.

**Review by Tuhinmia007 — COMMENTED** [review]
Good

**Comment by realdealshaman** [comment]
@coolestowl, thanks for the update. I understand there's some confusion about how we apply labels like 'none,' 'limited,' or 'yes' for tracking. We use 'limited' specifically when a privacy policy outlines a defined retention period, such as a week or a month. In this instance, we'll have to label tracking as 'yes' since no specific timeframe is provided. If the privacy policy is updated to include a precise duration for data retention, we can adjust the label to 'limited.' Thanks for your understanding.

**Comment by coolestowl** [comment]
I totally understand, thanks for the explanation and help!

**Pull request merged**
