### PR TITLE
Update to godwoken chain

### PR DESCRIPTION
**Pull request by lyledavids**
Update to godwoken chain based on the chainid given on https://startwithnervos.com/godwoken
However, the chainid on the current hosted version of chainlist is 
868455272153094

### CODE REVIEW

**Review by Kuzirashi — APPROVED** [review]

**Comment by realdealshaman** [comment]
@lyledavids @Kuzirashi hey, thanks for the PR. We are only able to enrich the info on chainlist via this repo(i.e. add more rpcs) to have the chain id updated please submit the PR here: https://github.com/ethereum-lists/chains

**Comment by Kuzirashi** [comment]
@realdealshaman 
Hey, we're waiting since May 9, 2022 for chainlist to review our PR - https://github.com/ethereum-lists/chains/pull/1146.

Is there any other way to verify that the chain ID is legit? :)

**Comment by Kuzirashi** [comment]
@realdealshaman 
Hey, we're waiting since May 9, 2022 for chainlist to review our PR - https://github.com/ethereum-lists/chains/pull/1146.

Is there anything we can do to streamline the process?

**Comment by Kuzirashi** [comment]
@realdealshaman 

Hello, our PR got merged to chainlist: https://github.com/ethereum-lists/chains/pull/1205

Are there any next steps? :)

**Comment by realdealshaman** [comment]
That's great! Nothing further needed here. Changes will reflect automatically

**Comment by realdealshaman** [comment]
@Kuzirashi hey, I hadn't noticed but it seems that the same rpc is being used for the testnet as the mainnet
https://godwoken-testnet-v1.ckbapp.dev
Is there supposed to be a different rpc for mainnet?

**Comment by Kuzirashi** [comment]
> @Kuzirashi hey, I hadn't noticed but it seems that the same rpc is being used for the testnet as the mainnet
> https://godwoken-testnet-v1.ckbapp.dev
> Is there supposed to be a different rpc for mainnet?

Hello, we don't have a mainnet release yet (we only know chain id at this point and wanted to reserve it). We expect mainnet it to be released in June.

We will update mainnet stuff here as soon as it comes out.

**Pull request merged**
