### PR TITLE
add additional holesky rpcs

### PR DESCRIPTION
**Pull request by 0xbid**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):

(public website in development)

#### Provide a link to your privacy policy:

N/A

#### If the RPC has none of the above and you still think it should be added, please explain why:

Reliable holesky RPCs are uncommon. The only ones currently available have high amounts of downtime.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@0xbid are these endpoints provided by PublicNode? if not then we cannot add privacy info for them that comes from the publicnode privacy policy

**Comment by 0xbid** [comment]
Thanks @realdealshaman, it has been updated with our privacy policy.

**Comment by realdealshaman** [comment]
@0xbid I can't reach the privacy policy using the link, is it live yet? If not, how long before it is available?

**Comment by nnnnnnsssss** [comment]
Okay

**Pull request closed without merging**
