### PR TITLE
Update extraRpcs.js for ZAN RPC

### PR DESCRIPTION
**Pull request by ZANDevelop**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://zan.top/home/node-service

#### Provide a link to your privacy policy:
https://a.zan.top/static/Privacy-Policy.pdf

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@ZANDevelop reading the privacy policy, it is stated that user information is collected: Meanwhile we may obtain and preserve information about your computer, such as IP address, hardware ID...

I can't find the specific quote you have added in this pr. Please update the quote and privacy tracking info

**Comment by ZANDevelop** [comment]
Thank you for your reply. The privacy policy in the link is intended for users who have registered on the ZAN official website. As the use of the key shown in Chainlist does not require registration on the website, we do not need to store user IP addresses or hardware ID... 
Therefore, we have removed the link and revised our privacy statement as follows:
ZAN Node Service does not track or store any kind of user information (such as IP addresses, location, request location, request data, etc.) that passes through our RPCs.

**Comment by realdealshaman** [comment]
@ZANDevelop unfortunately unless the statement matches whats on your website we cant accept it, we can however still list the rpc without the privacy policy

**Comment by ZANDevelop** [comment]
This paragraph states that 'we may preserve information about your computer such as IP address, hardware ID, etc.' when someone uses third-party services through the ZAN website. However, this statement is not applicable to users who use the RPC service on Chainlist.
We have updated our privacy policy to state that we track user computer IP addresses to provide our services. Please review the new privacy policy below：
ZAN Node Service generally does not store any kind of user information (e.g. IP address, location, requst location, request data, etc.) that transits through our RPCs except for one senario ——we may track your IP address when you are using our RPCs and will delete it immediately when you stoping using our RPCs. To learn more, please review our privacy policy at https://a.zan.top/static/Privacy-Policy.pdf

**Comment by realdealshaman** [comment]
@ZANDevelop can we set to "limited" tracking

**Comment by ZANDevelop** [comment]
OK  done

**Comment by realdealshaman** [comment]
I've added the changes manually to avoid the merge conficts

**Comment by ZANDevelop** [comment]
image

OK，thanks,  why the score is  ❌  ？

**Pull request closed without merging**
