### PR TITLE
Update 48Club RPC

### PR DESCRIPTION
**Pull request by 48ClubIan**
1. switch from bnb48.club to 48.club
2. add Hold-Koge-Discount RPC address

If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://www.48.club

#### Provide a link to your privacy policy:
https://docs.48.club/buidl/infrastructure/bsc-validator/enhanced-rpc

### CODE REVIEW

**Comment by realdealshaman** [comment]
@48ClubIan Hi, does 48Club have a privacy policy?

**Comment by 48ClubIan** [comment]
> @48ClubIan Hi, does 48Club have a privacy policy?
Is this a necessary item?
We have very simple description at https://docs.48.club
Do we need it to get merged ?

**Comment by realdealshaman** [comment]
@48ClubIan No, it isn't necessary but can you consider the last point on list above: If the RPC has none of the above and you still think it should be added, please explain why

**Comment by 48ClubIan** [comment]
Will start another pr from 48Club's repo

**Pull request closed without merging**
