### PR TITLE
feat: remove katla testnet

### PR DESCRIPTION
**Pull request by swarna1101**
Since the testnet **Taiko Katla** is deprecated, this PR is to remove it from chainlist.

### CODE REVIEW

**Comment by swarna1101** [comment]
Can you pls remove Katla testnet from chainlist, as it is deprecated
already PR here closed : https://github.com/ethereum-lists/chains/pull/5445
@realdealshaman

**Comment by realdealshaman** [comment]
Hey @swarna1101 thanks for the pr, I ran into some merge conflicts but I have proceeded to remove it manually. Thanks again

**Comment by swarna1101** [comment]
> Hey @swarna1101 thanks for the pr, I ran into some merge conflicts but I have proceeded to remove it manually. Thanks again

thanks a lot, we this gets fixed soon, and Katla gets removed

**Comment by swarna1101** [comment]
hey any update on this? @realdealshaman 
I can still see Katla: https://chainlist.org/chain/167009

**Pull request closed without merging**
