### PR TITLE
Update extraRpcs.json

### PR DESCRIPTION
**Pull request by supernftier**
add exlscan network

### CODE REVIEW

**Comment by supernftier** [comment]
add exlscan network

**Comment by realdealshaman** [comment]
Hey, thanks for the PR, new networks have to be added via the add your network button please. Please submit your request to the following repo: https://github.com/ethereum-lists/chains

**Review by BISHOy2580 — APPROVED** [review]
bishoymagdy33@gmail.com

**Comment by realdealshaman** [comment]
closing this PR from lack of changes. Please submit a new PR if you would like to have more rpcs added once it is merged here: https://github.com/ethereum-lists/chains

**Pull request closed without merging**
