### PR TITLE
Added Hypr Network

### PR DESCRIPTION
**Pull request by HyprMax**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://www.hypr.network

#### Provide a link to your privacy policy:
N/A - Hypr is a permissionless and decentralized open network. No data is collected.

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @HyprMax thanks for the pr! To get a new network added you'll need to submit a pull request here first:
https://github.com/ethereum-lists/chains

**Comment by HyprMax** [comment]
Thanks @realdealshaman - we requested the network to be added a while ago. Unfortunately it seems they hare a big backlog. https://github.com/ethereum-lists/chains/pull/4523

**Comment by realdealshaman** [comment]
@HyprMax thanks for the PR, I've added the listing manually to avoid merge conflicts. Thanks again

**Comment by HyprMax** [comment]
You rock, thank you @realdealshaman

**Pull request closed without merging**
