### PR TITLE
add c4ei

### PR DESCRIPTION
**Pull request by c4ei**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):

https://c4ei.net

#### Provide a link to your privacy policy:
https://c4ei.net/privacy.html

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @c4ei thanks for the PR to add C4ei, but to add a new network you need to submit a PR to the following repo first: https://github.com/ethereum-lists/chains

**Review by alokeutpal — APPROVED** [review]

**Review by c4ei — COMMENTED** [review]
@alokeutpal approved this pull request
thank you

**Review by c4ei — COMMENTED** [review]
What action should I take? I wonder if it's a merge on github or if I can just push it.
제가 어떤 액션을 취해야 할지요? github 에서 머지 되는 것인지 아니면 제가 push 하면 되는 것인지 궁금합니다.

**Comment by c4ei** [comment]
image

**Review by alokeutpal — APPROVED** [review]

**Comment by deckerj717** [comment]
I'm not understanding these directions

John decker

**Comment by c4ei** [comment]
i am sorry i don't know How To PR

i can't see like button
image

**Pull request closed without merging**
