### PR TITLE
Update extraRpcs.js

### PR DESCRIPTION
**Pull request by BelialNarcissus**
Add nodeconnect rpc

If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi, @BelialNarcissus looking into your privacy policy we would need to add this as the text:
2.2. Usage Data: We may collect information about how you interact with our Service. This may include information about your operating system, IP address, and browser type.
it was pulled from the link you provided. We also need to add tracking: to "yes"

**Comment by BelialNarcissus** [comment]
Our data collection is limited to website usage only, and we do not capture any data for RPC API interactions. If you have specific concerns or if you still recommend following the mentioned steps, please let me know.

**Comment by realdealshaman** [comment]
Yes, please. To have tracking as "none", the privacy policy has to state that user data is not stored

**Comment by BelialNarcissus** [comment]
Updated

**Pull request merged**
