### PR TITLE
Adding Tatum Ethereum RPC Node

### PR DESCRIPTION
**Pull request by blockchaingirl1407**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @blockchaingirl1407 thanks for the pr. Please use a direct quote from the privacy policy for the privacy statement. Tracking details should only be set to "none" if the privacy policy states that you do not collect any user info such as IP, wallet address etch while they use the rpc , if you collect log data and share with third parties it should be set to "yes", and if you can state how long you hold on to that info , a week , a month etc , then it can be set to "limited"

**Comment by Amarylla923** [comment]
Add

**Comment by blockchaingirl1407** [comment]
> Hi @blockchaingirl1407 thanks for the pr. Please use a direct quote from the privacy policy for the privacy statement. Tracking details should only be set to "none" if the privacy policy states that you do not collect any user info such as IP, wallet address etch while they use the rpc , if you collect log data and share with third parties it should be set to "yes", and if you can state how long you hold on to that info , a week , a month etc , then it can be set to "limited"

**Comment by blockchaingirl1407** [comment]
@realdealshaman, thank you for your comment; I edited the privacy policy quote and also put a yes for tracking. It is OK now?

**Pull request closed without merging**
