### PR TITLE
added Odyssey chain information

### PR DESCRIPTION
**Pull request by dreamdev2427**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://www.dioneprotocol.com/

#### Provide a link to your privacy policy:
https://www.dioneprotocol.com/legal/privacy

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by dreamdev2427** [comment]
How are you team members?
Would you kindly merge my PR and deploy website?

**Comment by realdealshaman** [comment]
Hey @dreamdev2427 thanks for the PR but, to add a new network, please submit a PR here first: https://github.com/ethereum-lists/chains

**Comment by dreamdev2427** [comment]
> Hey @dreamdev2427 thanks for the PR but, to add a new network, please submit a PR here first: https://github.com/ethereum-lists/chains

Yes, I already have pushed chain information to the repository and they merged my PR.
After did that, I have created PR to this repository.

**Comment by dreamdev2427** [comment]
How are you team members?
Would you kindly check my PR and merge it?

**Comment by dreamdev2427** [comment]
How are you team?
Would you kindly check?

**Comment by realdealshaman** [comment]
@dreamdev2427 thanks for the PR. We only need to add the chainID and rpc to the the extraRPC file, I've added it manually

There's no need to add it to the registry since it is not overwriting any chain and we only add chainids to the chainid.json once the chain is listed on DefiLlama. Thanks again

**Pull request closed without merging**
