### PR TITLE
Update chainIds.js

### PR DESCRIPTION
**Pull request by supernftier**
add exlscan network

### CODE REVIEW

**Comment by supernftier** [comment]
add chainid of exlscan network

**Comment by realdealshaman** [comment]
please see comment on pr #64

**Comment by realdealshaman** [comment]
closing this PR from lack of changes. Please submit a new PR if you would like to have more rpcs added once it is merged here: https://github.com/ethereum-lists/chains

**Comment by YozzaJovica** [comment]
Shame you all i give you all took and change what u like.GREED comes for all you

**Pull request closed without merging**
