### PR TITLE
remove ASK token - permission.io

### PR DESCRIPTION
**Pull request by gsalvador-permission**
we would like to remove our ASK token on your list

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi, the request needs to be submitted here: https://github.com/ethereum-lists/chains once it is removed there, it will no longer appear on the UI

**Comment by realdealshaman** [comment]
Hey @gsalvador-permission , why do you want to remove this network?

**Comment by gsalvador-permission** [comment]
Hi @realdealshaman Thank you for the heads up on ethereum-list/chain repository.

**Comment by YozzaJovica** [comment]
> Hi @realdealshaman Thank you for the heads up on ethereum-list/chain repository.
i give premision for this this is mine i create and he pull me out of this

**Pull request closed without merging**
