### PR TITLE
add classzz network

### PR DESCRIPTION
**Pull request by FranckStone**

### CODE REVIEW

**Comment by FranckStone** [comment]
update

**Comment by realdealshaman** [comment]
Are you looking to add a project to display your tvl or simply to have the ability to connect metamask to the network?

**Comment by FranckStone** [comment]
thanks add a network

**Comment by realdealshaman** [comment]
I see that you have submitted a PR here: https://github.com/ethereum-lists/chains. once the PR is merged there, the info will be available on our Chainlist page also

**Pull request closed without merging**
