### PR TITLE
Add Candle

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Is this the same chain as in this PR: https://github.com/DefiLlama/chainlist/pull/20 ?

**Comment by samisbakedham** [comment]
> Is this the same chain as in this PR: https://github.com/DefiLlama/chainlist/pull/20 ?

Yes

**Comment by realdealshaman** [comment]
Got it, we actually only need one PR. I've actually provided more info on the other, could we go ahead and close this one?

**Comment by samisbakedham** [comment]
> Got it, we actually only need one PR. I've actually provided more info on the other, could we go ahead and close this one?

Sounds good and thanks! I'll be sure to check the other PR and do as needed to finalize!

**Comment by realdealshaman** [comment]
going to close this one since it is just an extra

**Pull request closed without merging**
