### PR TITLE
Add evmos testnet RPC

### PR DESCRIPTION
**Pull request by jolube**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Thanks for the PR, for the changes to be reflected on the page, it is necessary to send a PR to ethereum-lists as well so that the new chainId is added: https://github.com/ethereum-lists/chains

**Comment by 0xngmi** [comment]
this just got merged in ethereum-lists so i guess no longer relevant?

**Comment by jolube** [comment]
Didn't realize this was for "additional" RPCs. Feel free to close.

**Comment by Imranch5690** [comment]
Evmos

**Comment by Imranch5690** [comment]
Prc

**Comment by Imranch5690** [comment]
Prcs

**Comment by Imranch5690** [comment]
Evmos prc

**Pull request closed without merging**
