### PR TITLE
feat: add hubble exchange chain - hubblenet

### PR DESCRIPTION
**Pull request by itsmnthn**
Adding new Perp Chain Hubble Exchange(Hubblenet). The PR is still open on [ethereum-lists/chains](https://github.com/ethereum-lists/chains/pull/4486) to add this chain to the list.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://www.hubble.exchange

#### If the RPC has none of the above and you still think it should be added, please explain why:
Terms & Condition don't have anything related to privacy policy but the RPC don't collect any information of the users and it's the public and only one rpc atm.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hey @itsmnthn to add a new network please submit a pull request here first: https://github.com/ethereum-lists/chains

**Comment by itsmnthn** [comment]
Hey @realdealshaman pull request to add new network to https://github.com/ethereum-lists/chains/pull/4486 is merged now

**Comment by realdealshaman** [comment]
@itsmnthn thanks for the ping, I'll merge but will remove hubblenet and areon from chainIds.json since we only use that to track the chains that have also been listed on DefiLlama. Thanks again

**Comment by itsmnthn** [comment]
> [realdealshaman](/realdealshaman)

Added this changes for these reasons
Want to add network related info like, tvl, bridged and stables with other protocol related adapters like, fees, revenue, derivative tvl etc.

**Pull request merged**
