### PR TITLE
Add evmos RPC

### PR DESCRIPTION
**Pull request by qubelabsio**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Review by nnnnnnsssss — CHANGES_REQUESTED** [review]
Recheck

**Review by qubelabsio — COMMENTED** [review]
sounds good, added website as well in PR

**Comment by realdealshaman** [comment]
@qubelabsio does your website have a privacy policy?

**Comment by qubelabsio** [comment]
> @qubelabsio does your website have a privacy policy?

Hey, we don't have one active at the moment.

**Pull request merged**
