### PR TITLE
Update extraRpcs.json

### PR DESCRIPTION
**Pull request by defido**
Add Autobahn.network

### CODE REVIEW

**Comment by realdealshaman** [comment]
If this is for a new network not yet on Chainlist page, it is necessary to get it added to this repo first: https://github.com/ethereum-lists/chains

**Comment by defido** [comment]
> If this is for a new network not yet on Chainlist page, it is necessary to get it added to this repo first: https://github.com/ethereum-lists/chains

OK, I will get onto that, thanks for the heads up!

**Comment by defido** [comment]
Thanks for assist @realdealshaman the changes were updated on the ethereum lists and merged

https://github.com/ethereum-lists/chains/pull/1019

> If this is for a new network not yet on Chainlist page, it is necessary to get it added to this repo first: https://github.com/ethereum-lists/chains

**Comment by realdealshaman** [comment]
not sure why he didn't merge it also. It was approved but still needs to be merged. Could you ask him if a timeframe for when it will be merged can be provided? I will merge on our end once he provides an expected time for the PR on ethereum-lists to be merged, thanks

**Comment by defido** [comment]
It has been merged 😎

**Comment by defido** [comment]
The network has been fully merged, both icon and the network, this is good to go!

**Pull request merged**
