### PR TITLE
Bc Hyper chain rpc added and it's privacy policy declaration

### PR DESCRIPTION
**Pull request by akashhalder3**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by akashhalder3** [comment]
I have added BC hyper chain rpc and PRIVACY POLICY please approve my request https://www.versatizecoin.com/

**Comment by akashhalder3** [comment]
please add the rpc

**Comment by realdealshaman** [comment]
Hey @akashhalder3 thanks for the PR. The privacy statement has to be quoted from your privacy policy. I found the following, please update your pr with this info and so that is displays tracking: yes and we can merge it:

When you use the Services, we may automatically process information about your computer and internet connection (including your IP address, operating system and browser type), your mobile carrier, device information (including device and application IDs), search terms, cookie information, as well as information about the timing, frequency and pattern of your service use, and information about to the transactions you make on our Services

**Comment by akashhalder3** [comment]
@realdealshaman Thank you for cooperating. I have updated the privacy statement and tracking: yes.

**Pull request merged**
