### PR TITLE
kekpoint: add chain 420420 KEK main net

### PR DESCRIPTION
**Pull request by ethgr0wth**
Kekchain is now Main Net "Kekistan" as release 0.1.3 is published https://github.com/kek-chain/go-kekchain/releases/tag/0.1.3

### CODE REVIEW

**Comment by billaure-crystaleum** [comment]
Kekchain Main Net "Kekistan"
RPC: https://mainnet.kekchain.com
Network ID: 103090
Chain ID: 420420 
Explorer: https://mainnet-explorer.kekchain.com

**Comment by billaure-crystaleum** [comment]
Submitted PR awaiting merge @ethereum-lists https://github.com/ethereum-lists/chains/pull/1626

**Comment by billaure-crystaleum** [comment]
Hi-yah. What's up can we merge this? Kek

**Comment by shopglobal** [comment]
Hi any word on merging this? Thanks, M

**Comment by billaure-crystaleum** [comment]
Hi-yah @defiLlama how are you? Hopefully this message finds you in good health and prosperity. Could we merge this? Community waiting. Thank you!

**Comment by billaure-crystaleum** [comment]
Hi-Yah @defillama can we get this merged? This PR is holding us back from merging with Sourcify https://github.com/ethereum/sourcify/pull/819

**Comment by realdealshaman** [comment]
@billaure-crystaleum Hi, we need to wait for the devs at the ethereum-lists repo to merge your PR. It will appear automatically on chainlist.org once it is merged, no need to do a repo here unless you want to add extra rpcs to a listing that has already been merged

**Comment by realdealshaman** [comment]
@billaure-crystaleum based on the info from the message above, can we close this pr?

**Comment by shopglobal** [comment]
@realdealshaman this branch is a green light go go go for merge. 

Thanks, [M](https://t.me/interchained)

**Comment by realdealshaman** [comment]
@shopglobal looks like Kekchain was given the chainid 420666, 
image

Will you update the info submitted to this PR?

**Comment by shopglobal** [comment]
> @shopglobal looks like Kekchain was given the chainid 420666, image
> 
> Will you update the info submitted to this PR?

420666 is testnet kektest on kekchain
420420 is mainnet kekistan on kekchain

Thanks,M

**Comment by realdealshaman** [comment]
Awesome, thank you. I have added the listings manually to avoid merge conflicts. Cheers

**Pull request closed without merging**
