### PR TITLE
Add RPCs for JIBCHAIN

### PR DESCRIPTION
**Pull request by nanthanwa**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://rpc-l1.jibchain.net is the official RPC (I put it in the first RPC) and I don't know about the privacy policy of their service. This is the official website: [https://jibchain.net/](https://jibchain.net/).

The second one RPC (https://jib-rpc.inan.in.th) is mine, so I'm maintaining this, and I put the privacy details on the same file.

#### Provide a link to your privacy policy:
-

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@nanthanwa is there a privacy policy available for RPC (https://jib-rpc.inan.in.th/) if not, we cannot add privacy info

**Comment by nanthanwa** [comment]
> @nanthanwa is there a privacy policy available for RPC (https://jib-rpc.inan.in.th/) if not, we cannot add privacy info
Hi @realdealshaman,
Can I declare the policy in `privacyStatement` like the others?

**Comment by nanthanwa** [comment]
Hi @realdealshaman, I've removed `privacyStatement` and changed the name of chain to JBC to follow the defillama website https://defillama.com/chain/JBC

**Comment by nanthanwa** [comment]
Hi @realdealshaman, sorry for interrupt you again,
I noticed that the logo for JBC is incorrect. How do I change the logo to the photo below?
JBC-logo

**Review by ibrahimkhled — CHANGES_REQUESTED** [review]
import { llamaNodesRpcs } from "./llamaNodesRpcs.js";

**Comment by nanthanwa** [comment]
Hi @ibrahimkhled sorry I don't understand, can you give me an example to do that? I didn't see anyone add logo by using that import.

And I have no idea how the logo https://icons.llamao.fi/icons/chains/rsz_jbc.jpg come for this chain 🤔 It was a 100% mistake  because this chain doesn't have any relative of this twitter https://twitter.com/ChainJib (I think the logo came from here)

the official twitter is: https://twitter.com/jibchain

**Pull request merged**
