### PR TITLE
Add Japan Open Chain Mainnet

### PR DESCRIPTION
**Pull request by 0xcuonghx**
Related to https://github.com/DefiLlama/icons/pull/1130

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @0xcuonghx is JOC already listed on DefiLlama? are we tracking any Defi projects on it?

**Comment by 0xcuonghx** [comment]
Hi @realdealshaman JOC hasn't listed anything yet on DefiLlama

**Comment by 0xcuonghx** [comment]
> Hi @0xcuonghx is JOC already listed on DefiLlama? are we tracking any Defi projects on it?
We just want to image icon visible on https://chainlist.org/. So Is that require?

**Comment by realdealshaman** [comment]
Thanks for the reply, we actually only add networks to chains.json once they have been listed on DefiLlama

**Comment by realdealshaman** [comment]
@0xcuonghx I am going to close this PR for now and I will add JOC to the file once we have listed some defi projects on it on DefiLlama

**Pull request closed without merging**
