### PR TITLE
Adding Engram Network

### PR DESCRIPTION
**Pull request by avenbreaks**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://engramnet.io
https://engramlabs.technology

PR New Chain : https://github.com/ethereum-lists/chains/pull/4029

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @avenbreaks thanks for the PR! If you'd like to add a new network please submit a pull request here: https://github.com/ethereum-lists/chains

**Comment by avenbreaks** [comment]
> Hi @avenbreaks thanks for the PR! If you'd like to add a new network please submit a pull request here: https://github.com/ethereum-lists/chains

Im already add on Chains you Can see PR on : https://github.com/ethereum-lists/chains/pull/4029

But i cannot see listed on Chainlist.. how i Can fix this issue ?

**Comment by realdealshaman** [comment]
@avenbreaks , looks good but I can't reach your privacy policy using the url provided, is there an issue?

**Comment by realdealshaman** [comment]
Hi @avenbreaks any update on this? if there is currently no privacy policy available we can simply add it without any of the tracking info and only add the rpcs

**Comment by realdealshaman** [comment]
added these manually to not include privacy policy since url provided does not work

**Pull request closed without merging**
