### PR TITLE
add ankr RPC for TAIKO Mainnet

### PR DESCRIPTION
**Pull request by swarna1101**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by swarna1101** [comment]
@realdealshaman can you check this pls

**Comment by realdealshaman** [comment]
Hey, @swarna1101 thanks for the pr, we already have an entry for taiko so I've added this rpc here: https://github.com/DefiLlama/chainlist/commit/0b99ad83072207b649c057b593237752ba222d5f

**Comment by realdealshaman** [comment]
Thanks again for the PR

**Comment by swarna1101** [comment]
thanks a lot

**Pull request closed without merging**
