### PR TITLE
Update extraRpcs.js

### PR DESCRIPTION
**Pull request by JoGetBlock**
Add GetBlock RPc endpoints to the list

If you are adding a new RPC, please answer the following questions.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@JoGetBlock thanks for the PR. You are adding the rpc to the goerli eth list. Is this where you intend to have it added?

**Comment by realdealshaman** [comment]
@JoGetBlock should this rpc be added under polygon?

**Comment by JoGetBlock** [comment]
> @JoGetBlock should this rpc be added under polygon?

I suppose so, maybe I've mistaken the pull request, this should be in the polygon endpoints sections

**Comment by realdealshaman** [comment]
I've added this rpc to the matic list manually

**Pull request closed without merging**
