### PR TITLE
Update extraRpcs.js - Haqq Network

### PR DESCRIPTION
**Pull request by kioqq**
Fixed wrong URL's for publicnode && add haqq dev team node

### CODE REVIEW

**Comment by realdealshaman** [comment]
Hi @kioqq thanks for the pull request
To add tracking info to these new rpcs, we also need to add a privacy statement from their privacy policy:
   {
        url: "https://evm.haqq.sh",
        tracking: "none"
      },
      {
        url: "wss://evm-ws.haqq.sh",
        tracking: "none"
      }
if no privacy policy is available, we have to add them with no tracking details

**Comment by kioqq** [comment]
Hi @realdealshaman! Done ✅ 
Thank you for your time ^^,

**Comment by realdealshaman** [comment]
Thanks @kioqq , can you also please provide the url to the privacy policy

**Comment by realdealshaman** [comment]
Sorry for the misunderstand, I see that they are publicnode rpcs, I've added them manually to avoid merge conflicts, thanks again for the pull request

**Pull request closed without merging**
