### PR TITLE
Update extraRpcs.js

### PR DESCRIPTION
**Pull request by 0xGery**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@0xGery does nocturnode have a privacy policy?

**Comment by 0xGery** [comment]
> @0xGery does nocturnode have a privacy policy?

N/A, However we did not store any user data, we will add Privacy Policy in near future

**Comment by realdealshaman** [comment]
@0xGery  got it, however we can't add tracking details if a privacy policy is not available, please update it so that the only the rpc is added by itself and we can get it merged

**Comment by 0xGery** [comment]
> @0xGery got it, however we can't add tracking details if a privacy policy is not available, please update it so that the only the rpc is added by itself and we can get it merged

is it works if I delete tracking details? 
Deleted tracking details

**Pull request merged**
