### PR TITLE
Update extraRpcs.js TECTUM

### PR DESCRIPTION
**Pull request by Farid116**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://softnote.com

#### Provide a link to your privacy policy:
https://tectum.io/privacy/

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by Farid116** [comment]
> @Farid116 thanks for the pr, to add a new network, please submit your PR to this repo first: https://github.com/ethereum-lists/chains

It's already done
Here is our file on
https://github.com/ethereum-lists/chains

_data/chains/eip155-1003.json

For some reason, by the link
https://chainlist.org/?search=tectum&testnets=false

our Tectum does not find it...why?

Is there anything else you need to do?

**Comment by Farid116** [comment]
> @Farid116 thanks for the pr, to add a new network, please submit your PR to this repo first: https://github.com/ethereum-lists/chains

We have appeared!
https://chainlist.org/?search=tectum

Is there anything else you need to do?

**Comment by Farid116** [comment]
> @Farid116 thanks for the pr, to add a new network, please submit your PR to this repo first: https://github.com/ethereum-lists/chains

Please help
on the website
https://chainlist.org/?search=tectum
when you click on
'add to metamask'
nothing happens...

**Comment by realdealshaman** [comment]
@Farid116, the RPC you provided might be blocking our pings or isn't accessible, as indicated by the red 'x' during our attempt to score it

**Comment by Farid116** [comment]
> @Farid116, the RPC you provided might be blocking our pings or isn't accessible, as indicated by the red 'x' during our attempt to score it

Please provide
the ip addresses of the ping servers.
This is necessary for our system administrator.

**Comment by Farid116** [comment]
> @Farid116, the RPC you provided might be blocking our pings or isn't accessible, as indicated by the red 'x' during our attempt to score it

Пожалуйста, сообщите,
что нужно сделать чтобы 
при нажатии на кнопку 'ADD METAMASK'
открывался Метамакс и предлагал добавить сеть .
Сейчас при нажатии 
на кнопку 'ADD METAMASK'
ничего не происходит...

**Pull request merged**
