### PR TITLE
Add Shardeum Testnet RPCs

### PR DESCRIPTION
**Pull request by swarna1101**
If you are adding a new RPC, please answer the following questions.

#### Provide a link to your privacy policy: https://shardeum.org/privacy-policy/

**Note:** These are replacements of old shardeum network details

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@swarna1101  , I appreciate the effort you put into the PR. However, there are a few adjustments required before we can proceed with merging:

1. The chainid.json file is specifically for chains already listed on DefiLlama. Kindly revert the modifications made there.
2. I noticed duplicate entries under the Sepolia testnet RPCs. Please address this.
3. Regarding the "none" tracking status you've added, it would be beneficial to include the specific line from your privacy policy that states you don't track any user information.

Once these are addressed, we can get this merged. Thanks

**Comment by swarna1101** [comment]
Hi @realdealshaman , Thanks for your response.
1. fixed this
2. One RPC is for our Shardeum Sphinx Validator 1.X and other one is for our Shardeum Sphinx Dapp 1.X
3. Fixed this to **Limited**

**Comment by realdealshaman** [comment]
@swarna1101, thanks for your follow-up. For us to include the tracking flag in the listing, we reference specific quotes from the privacy policy. I noted in Shardeum's privacy policy: 

"Shardeum follows a standard procedure of using log files. These files log visitors when they visit websites... The information collected by log files includes IP addresses, browser type, ISP, date and time stamp, referring/exit pages, and potentially the number of clicks." 

Based on this, the tracking should be marked as "yes". It would only be categorized as "limited" if the policy specifies the amount of time this information is saved before deletion.

**Comment by swarna1101** [comment]
Hi @realdealshaman , fixed it, Pls check once

**Pull request merged**
