### PR TITLE
Add Caduceus Network & RPCS

### PR DESCRIPTION
**Pull request by zikyfranky**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Need to submit your pr here: https://github.com/ethereum-lists/chains it is a new chain not on the list. We only add extrarpcs to existing listing at this repo

**Comment by zikyfranky** [comment]
> Need to submit your pr here: https://github.com/ethereum-lists/chains it is a new chain not on the list. We only add extrarpcs to existing listing at this repo

Thanks, already did, hopefully it gets merged and this can go through

**Comment by zikyfranky** [comment]
@realdealshaman
My PR on the /ethereum-lists/chains repo just got approved.

Do you think you could allow this through?

**Comment by realdealshaman** [comment]
It happens automatically, you can see [CMP-Mainnet](https://chainlist.org/chain/256256) is already on the chainlist site since it was accepted on the ethereum-lists repo. If you need to add new rpcs to the list in the future, we can add them through this repo

**Pull request merged**
