### PR TITLE
0x0000000000000000000000000000000000001000

### PR DESCRIPTION
**Pull request by ponury1990**
please help me with the system reward

### CODE REVIEW

**Comment by realdealshaman** [comment]
these are quite a lot of changes, could you provide a short summary of them and why you'd like to make them?

**Comment by ponury1990** [comment]
chciałbym żeby to ruszyło i saldo konta wyglądało inaczej niz 0

**Review by YozzaJovica — COMMENTED** [review]
what i have pf all this u use my work and i will abort all

**Review by YozzaJovica — APPROVED** [review]

**Comment by dianauyuuuuu** [comment]
haksh

**Pull request closed without merging**
