### PR TITLE
Add Oragon Network Testnet

### PR DESCRIPTION
**Pull request by SeftzZz**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
[oragon.network](https://oragon.network)
[rpc oragon,network testnet](https://rpc.oragon.network/node/ethereum_api)

#### Provide a link to your privacy policy:
[Privacy Policy](https://oragon.network/privacy-policy.html)

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by SeftzZz** [comment]
we have authorize it

**Comment by realdealshaman** [comment]
Hey, @SeftzZz thanks for submitting the PR! to add a new network please submit the pull request here first: https://github.com/ethereum-lists/chains

**Comment by SeftzZz** [comment]
Hey @Real Shaman thanks for reply, i will submit the pull request.

Pada Kam, 29 Agu 2024 01.19, Real Shaman ***@***.***> menulis:

**Comment by SeftzZz** [comment]
we have resolve conflicts

**Comment by OragonXTeknologi** [comment]
Hai @realdealshaman we have resolve the conflict, can you process this request ?

**Comment by realdealshaman** [comment]
@SeftzZz the way to get a new network listed is to submit a pull request here: https://github.com/ethereum-lists/chains Have you already submitted your pull request there?

**Comment by SeftzZz** [comment]
@realdealshaman yes we have already submitted pull request there

**Review by thechillday1 — APPROVED** [review]

**Review by thechillday1 — CHANGES_REQUESTED** [review]
Send it back

**Comment by SeftzZz** [comment]
@thechillday1 hello, we have send it back

**Comment by realdealshaman** [comment]
@SeftzZz thanks for submitting the PR to the ethereum-lists repo! Once it is merged there it will appear on chainlist.com also

**Pull request closed without merging**
