### PR TITLE
feat: add LlamaNodes Free RPCs (ETH & Polygon)

### PR DESCRIPTION
**Pull request by brenopolanski**

### CODE REVIEW

**Comment by 0xStrobe** [comment]
should we merged this?

**Comment by brenopolanski** [comment]
> should we merged this?

Hey @0xStrobe, Not yet! Waiting for confirmation from other team members (LlamaNodes).

**Comment by brenopolanski** [comment]
Hey @0xStrobe, can you review this PR? Feel free to merge it if everything is fine 🦙

**Comment by Seyifash16** [comment]
Good luck

**Pull request merged**
