### PR TITLE
Update extraRpcs.json

### PR DESCRIPTION
**Pull request by bladepool**
adding 6066 chainid rpc for Tres Leches Finance

### CODE REVIEW

**Comment by realdealshaman** [comment]
A PR needs to be submitted here to have a new chain added : https://github.com/ethereum-lists/chains

Once they merge the PR there it will also appear on chainlist.org

**Comment by bladepool** [comment]
PR requested on chains Tres Leches Mainet Update #1631, waiting for approval.

**Comment by realdealshaman** [comment]
Hey, @bladepool can we close this PR? A PR is not needed to add a new network. The network will appear on chainlist.org once it is merged in the ethereum-lists repo

**Comment by bladepool** [comment]
> Hey, @bladepool can we close this PR? A PR is not needed to add a new network. The network will appear on chainlist.org once it is merged in the ethereum-lists repo

closed thanks

**Pull request closed without merging**
