### PR TITLE
add polysplit rpc for chain ids 56 and 1

### PR DESCRIPTION
**Pull request by kotsmile**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
https://polysplit.cloud

#### Provide a link to your privacy policy:
https://polysplit.cloud/privacy

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@kotsmile thanks for the PR, to have tracking details as "none" your privacy policy must state that you do not track the IP address or other user info

Please set to "yes" or is possible update the privacy policy to reflect this info. Thanks

**Comment by kotsmile** [comment]
> @kotsmile thanks for the PR, to have tracking details as "none" your privacy policy must state that you do not track the IP address or other user info
> 
> Please set to "yes" or is possible update the privacy policy to reflect this info. Thanks

Thank you for mentioning this. The privacy policy has been corrected

**Comment by realdealshaman** [comment]
@kotsmile thanks, I've added the entries manually to avoid merge commits :+1:

**Comment by kotsmile** [comment]
@realdealshaman thanks! can you help me please, why chainlist.org does not have polysplit rpcs?

**Pull request closed without merging**
