### PR TITLE
Update chainIds.js

### PR DESCRIPTION
**Pull request by supernftier**
update exlscan to excoincial

### CODE REVIEW

**Comment by supernftier** [comment]
add excoincial network

**Comment by Whitetrashme** [comment]
https://github.com/DefiLlama/chainlist/pull/66.diff

**Comment by Whitetrashme** [comment]
> https://patch-diff.githubusercontent.com/raw/DefiLlama/chainlist/pull/66.patch

**Comment by realdealshaman** [comment]
Have you already submitted a PR to the ethereum-lists repo? https://github.com/ethereum-lists/chains

**Comment by Whiteme01** [comment]
Merga

**Comment by Whiteme01** [comment]
> add excoincial network

f671c06f754fc44c362ccb3e3cedf91d11e16c14

**Comment by Whiteme01** [comment]
> Have you already submitted a PR to the ethereum-lists repo? https://github.com/ethereum-lists/chains

No

**Comment by realdealshaman** [comment]
You need to send your request to this repo: https://github.com/ethereum-lists/chains

**Review by lokera666 — APPROVED** [review]

**Comment by realdealshaman** [comment]
closing this PR from lack of changes. Please submit a new PR if you would like to have more rpcs added once it is merged here: https://github.com/ethereum-lists/chains

**Pull request closed without merging**
