### PR TITLE
add network

### PR DESCRIPTION
**Pull request by jakubartur**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by realdealshaman** [comment]
@jakubartur to get a new network added you need to submit a PR here: https://github.com/ethereum-lists/chains

**Comment by Brayan9327** [comment]
> If you are adding a new RPC, please answer the following questions.
> 
> #### Link the service provider's website (the company/protocol/individual providing the RPC):
> 
> 
> #### Provide a link to your privacy policy:
> 
> 
> #### If the RPC has none of the above and you still think it should be added, please explain why:
> 
> Your RPC should always be added at the end of the array.

**Comment by realdealshaman** [comment]
@jakubartur please remove changes to package.json, package-lock.json and yarn.lock

**Comment by realdealshaman** [comment]
Once those changes are removed I can merge this PR

**Comment by realdealshaman** [comment]
I've added the listing manually

**Pull request closed without merging**
