### PR TITLE
Update chainIds.json

### PR DESCRIPTION
**Pull request by thINKoor**
If you are adding a new RPC, please answer the following questions.

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Comment by thINKoor** [comment]
Hey folks, happy to make any changes or defer to your team. Just wanted to get the PR opened and solidify ownership of this chainId.

**Comment by realdealshaman** [comment]
Hey @thINKoor thanks for the PR but to add a new network please submit your pull request here first: https://github.com/ethereum-lists/chains

**Comment by drwasho** [comment]
PR made here @realdealshaman by @thINKoor: https://github.com/ethereum-lists/chains/pull/6091

**Comment by realdealshaman** [comment]
Hey, once it is merged at ethereum-lists it will also appear on chainlist.org

**Comment by CruzMolina** [comment]
cc @Garrikk90

**Pull request closed without merging**
