### PR TITLE
Blockswap Goerli Builder RPC

### PR DESCRIPTION
**Pull request by pon-pbs**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):

https://pon.network/

#### Provide a link to your privacy policy:

```
Blockswap RPC does not track any kind of user information (i.e. IP, location, etc.) nor is any information logged. All blocks are encrypted when passed between proposers, builders, relayers, and Ethereum. It does not transmit any transactions to the relayer.
```

### CODE REVIEW

**Comment by realdealshaman** [comment]
@pon-pbs thanks for the pr, looks good however, for the privacy policy statement we need to use a quote directly from your privacy policy, in the case of IP being tracked for analytics, the tracking would have to be set to "yes" unless a time period is given for when they are deleted. For a tracking "no" to be added the privacy policy would have to quote that IP address, user info is not tracked

**Comment by realdealshaman** [comment]
@pon-pbs can you change the privacy statement to state that you track the IP for analytics: 

We use analytical cookies to see, for example, which content on the Site is highly frequented and also to analyze if content should be updated or improved. These cookies are also used to provide you with personalized content based on the pages you have shown interest in. These cookies process and save data like your browser type, referrer URLs, operating system, date/time stamp, views and clicks on the Site, and your (truncated) IP address

and update tracking to "yes"

**Comment by pon-pbs** [comment]
@realdealshaman We will take a look and revert back as soon as possible. Thanks for taking a look in the mean time! Appreciate it.

**Comment by pon-pbs** [comment]
image

**Comment by pon-pbs** [comment]
hey @realdealshaman thanks for merging. we checked things on our side are working but chain list is not showing block height, latency etc. Let us know if you can see any issues on your end

**Pull request merged**
