### PR TITLE
Update chains.js

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Comment by realdealshaman** [comment]
Are you also adding a protocol running on candle, to be listed on Defillama?

**Comment by samisbakedham** [comment]
> Are you also adding a protocol running on candle, to be listed on Defillama?

Yes i think so

**Comment by realdealshaman** [comment]
Not essential. The more important part is having the adapter/code that provides your protocol's TVL

**Comment by samisbakedham** [comment]
> Not essential. The more important part is having the adapter/code that provides your protocol's TVL

Do you have a discord server where we could open a private thread to discuss a road map for implementation? Would love to have some clear goals and work directly with your team

**Comment by realdealshaman** [comment]
Here is our Discord link: Join the community: [http://discord.gg/buPFYXzDDd](https://t.co/IIf3mE8UU2)

**Comment by samisbakedham** [comment]
Hey can we merge this?

**Comment by realdealshaman** [comment]
provided some additional info on our discord. Lets keep the chat going there please

**Pull request merged**
