### PR TITLE
Updated Klaytn Testnet endpoint and allthatnode urls

### PR DESCRIPTION
**Pull request by praveen-klaytn**
If you are adding a new RPC, please answer the following questions.

#### Link the service provider's website (the company/protocol/individual providing the RPC):
* Updated the Klaytn Testnet url https://klaytn.foundation/kaia-testnet-kairos-launch/
* Updated the Allthatnode urls of Klaytn https://www.allthatnode.com/klaytn.dsrv

#### If the RPC has none of the above and you still think it should be added, please explain why:

Your RPC should always be added at the end of the array.

### CODE REVIEW

**Review by Amarylla923 — COMMENTED** [review]
No approval. No changes. I don't know who you are. I don't know any of you .

**Comment by praveen-klaytn** [comment]
Hi @Amarylla923 , I am Praveen from Klaytn Foundation. May i know whats the approval process. I would like to change update rpc urls of Klaytn for recent updates of Kairos Testnet and also the Allthatnode rpc url changes. 
I also have attached the reference links.

**Comment by Amarylla923** [comment]
I àm unfamiliar with any of this. And if you would be kind enough to
explain what this defillama chain list is about. Does it effect currency as
in any that is mine or in my control or set to be mine or my descendants.
Is it just a fun haha get to know people maybe advertise or direct flow of
internet browsing? Is this alt coins in the making going to lead to more
universal currency? I cannot approve what I do not understand. Which at
times one does, and hopes for the best. So kindly if you can briefly
explain what is defillama.

**Comment by praveen-klaytn** [comment]
@Amarylla923 , Looks like it auto assigned to you by Defillama. you may ignore if you are not part of this. Thanks.

**Comment by Amarylla923** [comment]
I am it. That is why I am wondering what it means to you, because I was
just learning the git hub system when this happened so I am curious as to
why everyone has merged onto this chain. Is it just sort of for nothing? Or
is there an actual reason. Like is this a chain link or some sort of
network for advertising is there an outcome? Why did you join or merge to
the branch defillama? All the other works I've done or committed to, no one
has merged . This defillama over 1000 mergers. I àlso am curious what does
defillama mean? I thank you kindly for the time and consideration in
responding to me.
Amarylla

**Comment by praveen-klaytn** [comment]
Hi @Amarylla923 , so this is to add a chain or update. As you see Klaytn 2 networks here https://chainlist.org/?search=klaytn&testnets=true . Now i wanted to update in chainlist website for Klaytn Testnet name mentioned here in the url as we are going through rebranding https://klaytn.foundation/kaia-testnet-kairos-launch/ . So klaytn endpoint rpc urls and the name will be replaced according to the Kaia timeline

**Comment by Amarylla923** [comment]
Hmm. I am unclear what this means. But ok, does this have to do with money?
Or are you revamping an existing coin or something? I mean I am pretty
curious because like I said I am pretty sure I began this, but possibly not

**Comment by praveen-klaytn** [comment]
No @Amarylla923 . This repository is to help developers  to easily add Network in Metamask.

**Review by Karim8090 — COMMENTED** [review]
55555

**Comment by praveen-klaytn** [comment]
@realdealshaman ,  could you please help reviewing this PR. Thanks.

**Comment by Karim8090** [comment]
okay

**Pull request merged**
